### ISSUE TITLE
Need a logo!

### ISSUE THREAD

**Issue by micheleriva** [micheleriva/mjn#1]
Is there someone who wants to make a beautiful logo for this project? 😄

**Comment by equinusocio** [comment]
I will make it. Just something simple.

**Comment by equinusocio** [comment]
[mjn.zip](https://github.com/micheleriva/mjn/files/2703414/mjn.zip)

**Comment by micheleriva** [comment]
@equinusocio hero! Feel free to add yourself to the list of contributors 🎉

**Comment by micheleriva** [comment]
@all-contributors please add @equinusocio for design

**Comment by micheleriva** [comment]
@all-contributors please add @adamlacombe for fix
