### ISSUE TITLE
What are the differences from lodash.get

### ISSUE THREAD

**Issue by steelbrain** [micheleriva/mjn#3]
Hi 👋 

The usage and API of this package looks really similar to [`_.get](https://lodash.com/docs/latest#get). Is there any differences between the two that you are aware of?

**Comment by micheleriva** [comment]
Hi @steelbrain !
That's a good question! I've never used Lodash so far, and I just inspected its code.
I tried to solve the problem with a similar philosophy, and if you are familiar with Lodash (or you're already using it), it should work the same way as Mjn.
The main difference here is that I worked a lot optimizing the code so, as you can see here, with Mjn you get only a tiny 307bytes (gziped) script, versus the 1.8kb (gziped) Lodash method.

Sources: 
Mjn: https://bundlephobia.com/result?p=mjn@0.1.1
_.get: https://bundlephobia.com/result?p=lodash.get@4.4.2

I think that in 2018, where people are working with Preact, Hyper, Inferno etc., 307bytes vs 1.8ks is a great deal 😄

**Comment by steelbrain** [comment]
The project looks fun, did not intend to undermine its usefulness. My apologies.
Thank you for the explanation.

**Comment by micheleriva** [comment]
@steelbrain no need to apologize, it was a great question 🙂 
Maybe I have to specify in some way that this can be a lighter alternative to _.get!
Thanks a lot 😄
